SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;
SELECT STREET_ADDRESS,POSTAL_CODE FROM LOCATIONS;

SELECT * FROM COUNTRIES;
SELECT * FROM JOBS;

SELECT STREET_ADDRESS,POSTAL_CODE from LOCATIONS;

select DEPARTMENT_NAME from DEPARTMENTS;
select REGION_NAME from REGIONS;







