SELECT * from EMPLOYEES;

SELECT STREET_ADDRESS,POSTAL_CODE from LOCATIONS;
SELECT DISTINCT FIRST_NAME from EMPLOYEES;
SELECT Distinct JOB_ID from EMPLOYEES;
SELECT DISTINCT COUNTRY_ID from LOCATIONS;
SELECT DISTINCT JOB_ID from JOBS;







