SELECT * FROM EMPLOYEES
WHERE SALARY between 6000 and 10000;


SELECT FIRST_NAME, SALARY from EMPLOYEES
WHERE SALARY BETWEEN 7000 and 10000;

SELECT * from EMPLOYEES
where JOB_ID = 'IT-PROG' or JOB_ID='SA_REP';