SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' or JOB_ID='SA_REP' or JOB_ID='ST_MAN' or JOB_ID='MK_REP';

SELECT * FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG','SA_REP','ST_MAN','MK_REP');

SELECT CITY,COUNTRY_ID from LOCATIONS
where COUNTRY_ID IN('IT','US','GB')
