SELECT * FROM EMPLOYEES
WHERE SALARY > 6000  ;

SELECT * FROM EMPLOYEES
WHERE SALARY > 6000 and SALARY < 10000;

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE FIRST_NAME = 'David';

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE FIRST_NAME = 'David' and LAST_NAME = 'Lee';