SELECT * FROM EMPLOYEES;

-- get me how many different departments we have for each location_id
SELECT * FROM DEPARTMENTS;
SELECT COUNT(*) FROM DEPARTMENTS;
SELECT COUNT(LOCATION_ID) FROM DEPARTMENTS;
SELECT LOCATION_ID FROM DEPARTMENTS;

SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS;
SELECT COUNT (DISTINCT LOCATION_ID) FROM DEPARTMENTS;

SELECT LOCATION_ID, COUNT (*) as "Total Count For Each LI" FROM DEPARTMENTS
GROUP BY  LOCATION_ID;


-- get me how many locations we have for each country_id
SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS
GROUP BY COUNTRY_ID
order by COUNTRY_ID ASC; --same thing -- > order by COUNTRY_ID;

SELECT * FROM LOCATIONS;



-- get me how many countries we have for each region
SELECT * FROM COUNTRIES;

SELECT REGION_ID, COUNT(*) FROM COUNTRIES
group by REGION_ID
ORDER BY REGION_ID DESC;





